---
output:
  html_document: default
  pdf_document: default
---
<h2>Load Packages</h2>
```{r, warning=F}
library(aso)
library(DT)
```

<h2>Read Plate and Plate Map Annotations</h2>
```{r}

# paths to supplied example data files, ref plate, expt plate and plate-map annotation file
refPlatePath <- system.file ("extdata","05272022_Stemonix_plate3_BL_n001_Pro2.statAll", package="aso")
exptPlatePath <- system.file ("extdata","05272022_Stemonix_plate3_60mins_n001_Pro2.statAll", package="aso")
plateMapPath <- system.file ("extdata","Stemonix_plate3_plate_map.csv", package="aso")

# create plate objects with data
refPlate <- aso::read_stemonix_data(refPlatePath)
exptPlate <- aso::read_stemonix_data(exptPlatePath)

# add the platemap to plates
refPlate <- aso:::read_stemonix_metadata(plateMapPath, refPlate)
exptPlate <- aso:::read_stemonix_metadata(plateMapPath, exptPlate)

```

<h2>Basic QC for Missing Data on Each Parameter</h2>
```{r}
# Encode discrete parameters where needed
# Replacing discrete values with numeric levels
refPlate <- aso::encodeDiscreteParameters(refPlate, parameter =  "Peak Spacing Regularity",textValues = c("OK", "IRREG", "Blank"), numericValues = c(1,-1,NA))
exptPlate <- aso::encodeDiscreteParameters(exptPlate, parameter =  "Peak Spacing Regularity",textValues = c("OK", "IRREG", "Blank"), numericValues = c(1,-1,NA))

# basic QC for missing data for each input parameter
refMissingDataReport <- aso::missingDataReport(refPlate, plateSize = 384)
exptMissingDataReport <- aso::missingDataReport(exptPlate, plateSize = 384)

# display the missing data report
DT::datatable(refMissingDataReport)
DT::datatable(exptMissingDataReport)

# bar chart of data disposition
p <- aso:::missingPlateDataChart(refPlate, plateSize = 384) 
p

# example with VERY stringent filters, drop parameters with > 5 missing values. 
refPlate <- aso:::filterLowDataParameters(refPlate, thresholdType = 'well_count', missingDataThreshold = 5)
exptPlate <- aso:::filterLowDataParameters(exptPlate, thresholdType = 'well_count', missingDataThreshold = 5)


```
<h2>Make a Plate Set, Labeling Plates, Harmonize Parameters</h2>
```{r}
# create a plateset object to hold the plates and transformed data
plateSet <- new("plateset")
plateSet <- addPlate(plateSet, refPlate, "ref")
plateSet <- addPlate(plateSet, exptPlate, "60mins")

# plates may contain different parameters after filtering
# this makes all plates contain the same (consistent) parameters
# consider if this should be automatic when adding plates or an option to run through
plateSet <- aso:::harmonizeParametersAcrossPlates(plateSet)


```

<h2>Data Transformation Example, log2ratio of 60mins plate vs ref</h2>
```{r}

# add a data transformation (log2ratio in this case), between the 60mins plate and ref plate
# the plateset holds data transformations
plates <- c("ref","60mins")

# (plateSet, platePair, method = 'log2ratio', bkgrdCorr=F, bkgrdSamples = NULL, bkgrdMode = 'median')
plateSet <- aso:::dataTransform(plateSet=plateSet, platePair=plates, method='log2ratio', bkgrdCorr=F)

```

<h2>Plot Example Plate Views</h2>
```{r}

# select a couple example parameters, this could be a list of parameter names
paramsToPlot <- exptPlate@statList[c(3,4)]
paramsToPlot

# NOTE: plateData contains well_id column which I get rid of here. Well_id could be kept as rownames
refPlate@plateData <- refPlate@plateData[-1]
exptPlate@plateData <- exptPlate@plateData[-1]

# this returns a grid of plate views, ref, 60min and the log2ratio plate views for each parameterToPlot
grid <- aso:::trellisPlateSetViewsPairViews(plateSet=plateSet, platePair=c("ref","60mins"), paramsToPlot = paramsToPlot,
                                            showRowColumnLabels = F, maxSatCount = 30, showLegend = F,
                                            tMethod = 'log2ratio', ggplot=T, elementDividers = F)

gridExtra::grid.arrange(grid)


```

<h2>Select a set of samples and plot associated bar charts covering paramsToPlot</h2>
```{r}
samples <- c("ASO5","ASO6","ASO7", "Veh1")

p <- aso:::getBarChartTrellis(plateSet=plateSet, samples = samples, parameters = paramsToPlot, samplesIn = 'rows', tMethod = 'log2Ratio')

gridExtra::grid.arrange(p)
```











